import Head from 'next/head'
import React, { FC } from 'react'

interface QuestionProps {
  [key: string]: any
}

/**
 * C 端 H5 的 url 规则：
 * http://localhost:3000/question/222
 */
const Question: FC<QuestionProps> = (props: QuestionProps) => {
  return (
    <>
        <Head>
            <title>Question Page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            Question Page
            <p>{props.id}</p>
        </main>
    </>
  )
}

export async function getServerSideProps(content: any) {
    const { id = '' } = content.params
    // 根据 id await 获取问卷数据
    return {
        props: {
            id
        }
    }
}

export default Question